config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'projects#index'

  get '/ui' => 'pages#ui'
  post '/tools/detect-bias' => 'tools#detect_bias'

  devise_for :users,
            path_names: { 
              sign_up: 'register', 
              sign_in: 'login', 
              sign_out: 'logout' 
            },
            controllers: { registrations: 'users', sessions: 'sessions' }

  resources :projects do
    get :pads
    get :checklist_report

    resources :collaborators, only: [:index, :destroy] do
      post :invite, on: :collection
      get :suggest, on: :collection
      put :promote, on: :member
    end

    resources :checklists, only: [:index] do
      put :check, on: :collection
    end

    resources :project_pads, only: [:new, :create, :edit, :update, :destroy]
    resources :queries
    resources :meme_mappers
  end
end

app/models/meme_mapper.rb
# == Schema Information
#
# Table name: meme_mappers
#
#  id              :integer          not null, primary key
#  project_id      :integer          not null
#  name            :string
#  image_url       :string           not null
#  serialized_data :binary           default(""), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Foreign Keys
#
#  fk_rails_0b67925060  (project_id => projects.id)
#

class MemeMapper < ApplicationRecord
  belongs_to :project

  validates :image_url, presence: true

  def data
    @data ||= JSON.parse(ActiveSupport::Gzip.decompress(self.serialized_data))
  end

  def data=(data)
    json = data.to_json
    @data = JSON.parse(json) # make sure data is always access with the same encoding
    self.serialized_data = ActiveSupport::Gzip.compress(json)
  end
end

app/controllers/meme_mappers_controller.rb
class MemeMappersController < ApplicationController
  helper_method :project, :meme_mapper, :presenter
  before_action -> { authorize(project, :collaborate?) }

  def index
    @meme_mappers = project.meme_mappers.order('created_at DESC')
    respond_to(&:js)
  end

  def new
    @meme_mapper = MemeMapper.new(project: project)
    respond_to(&:js)
  end

  def create
    @meme_mapper = MemeMapper.new(meme_mapper_params)
    MemeMappers::Save.(meme_mapper: meme_mapper, fetch_data: true)
    redirect_to project_meme_mapper_path(project, @meme_mapper)
  end

  def show
    params[:page] ||= 1
    respond_to(&:js)
  end

  def edit
  end

  def update
    meme_mapper.update_attributes(meme_mapper_params)
    MemeMappers::Save.(meme_mapper: meme_mapper, fetch_data: false)
    redirect_to project_meme_mappers_path(project)
  rescue ActiveRecord::RecordInvalid
    render :edit
    respond_to(&:js)
  end

  def destroy
    meme_mapper.destroy!
    respond_to(&:js)
  end

  private

  def project
    @project ||= Project.find(params[:project_id])
  end

  def meme_mapper
    @meme_mapper ||= MemeMapper.find(params[:id])
  end

  def meme_mapper_params
    params.require(:meme_mapper).permit(:name, :image_url).merge(project: project)
  end

  def presenter
    @presenter ||= MemeMapperPresenter.new(meme_mapper)
  end
end

app/views/meme_mappers/_edit.html.erb
<%= form_for [project, meme_mapper], remote: true do |f| %>
  <div class="modal-body">
    <div class="errors-placeholder"></div>

    <%= render 'shared/errors', errors: meme_mapper.errors %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="modal-footer">
    <div class="form-group">
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('general.close') %></button>
      <%= f.submit t('tools.meme_mapper.save'), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/meme_mappers/_index.html.erb
<div class="spacing-v"></div>
<div class="pull-right">
  <%= link_to new_project_meme_mapper_path(project), remote: true do %>
    <span class="fa fa-close trigger-close-searches"></span>
  <% end %>
</div>

<h2 class="h4"><%= t('tools.meme_mapper.heading') %></h2>
<div class="spacing-half-v"></div>
<h3 class="h5">
  <%= t('tools.meme_mapper.saved_searches') %>
  <i class="glyphicon glyphicon-refresh spinning hide"></i>
</h3>

<table class="table table-hover table-striped table-bordered">
  <tbody>
    <% for meme_mapper in @meme_mappers do %>
      <tr>
        <td>
          <%= meme_mapper.created_at %>
        </td>
        <td>
          <%= link_to meme_mapper.name || meme_mapper.image_url, project_meme_mapper_path(project, meme_mapper), remote: true %>
        </td>
        <td>
          <%= link_to t('tools.meme_mapper.edit'), edit_project_meme_mapper_path(project, meme_mapper), remote: true, data: { toggle: 'modal', target: '#modal' } %>
          <%= link_to t('tools.meme_mapper.delete'), project_meme_mapper_path(project, meme_mapper), method: :delete, remote: true, data: { confirm: t('tools.media_cloud.confirm') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/meme_mappers/_new.html.erb
<div class="flex flex-wrap spacing-2-v">
  <h2 class="h4 margin-reset"><%= t('tools.meme_mapper.heading') %></h2>
  <ul class="list-unstyled clearfix list-mc-searches">
    <li class="pull-right font-size-sm">
      <%= link_to t('tools.meme_mapper.saved_searches'), project_meme_mappers_path(project), class: '', remote: true %>
      <span>|</span>
      <a href="https://tineye.com" target="_blank">
        <%= image_tag 'logos/tineye-logo.jpg', alt: '', width: '32' %>
        <span class="fa fa-external-link"></span>
      </a>
    </li>
  </ul>
</div>

<%= form_for [project, @meme_mapper], remote: true do |f| %>
  <%= render 'shared/errors', errors: @meme_mapper.errors %>

  <%= f.label :image_url, t('tools.meme_mapper.image_url') %>
  <div class="form-group flex row-sm flex-align-center">
    <div class="gutter-sm flex-1">
      <%= f.text_field :image_url, class: 'form-control' %>
    </div>
    <div class="gutter-sm">
      <button class="btn btn-primary">
        <i class="glyphicon glyphicon-refresh spinning hide"></i>
        <span class="text"><%= t('tools.meme_mapper.submit') %></span>
      </button>
    </div>
  </div>
<% end %>

<div class="well">
  <p>
    <%= raw t('tools.meme_mapper.instructions') %>
  </p>
</div>

app/views/meme_mappers/_show.html.erb
<div class="spacing-2-v font-size-sm clearfix">
  <div class="pull-right">
    <span>
      <%= link_to 'New search', new_project_meme_mapper_path(project), remote: true %>
    </span>
    <span>|</span>
    <span>
      <%= link_to 'Saved searches', project_meme_mappers_path(project), remote: true %>
    </span>
  </div>
</div>

<% unless meme_mapper.name.present? %>
  <p>
    <%= link_to 'Save Search', edit_project_meme_mapper_path(project, meme_mapper), class: 'btn btn-primary', remote: true, data: { toggle: 'modal', target: '#modal' } %>
  </p>
<% end %>

<div class="well">
  <div class="h5">
    <%= presenter.result_count %> results
  </div>

  <p>
    for: <%= link_to presenter.image_url, presenter.image_url %>
  </p>
</div>

<% backlinks = Kaminari.paginate_array(presenter.backlinks).page(params[:page]).per(10) %>

<div class="well">
  <div class="pull-right">
    <i class="glyphicon glyphicon-refresh spinning hide"></i>
  </div>

  <%= paginate backlinks, remote: true %>
</div>

<div class="well">
  <table class="table margin-reset">
    <tbody>
      <% for match in backlinks do %>
        <tr>
          <td>
            <img src="<%= match.image_url %>" style="max-width: 300px;" />
          </td>
        </tr>
        <% for backlink in match.backlinks do %>
          <tr>
            <td>
              Crawled on <%= backlink.date %>
              <br>
              <%= link_to backlink.link, backlink.link %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/meme_mappers/destroy.js.erb
$(function () {
  $.getScript('<%= j project_meme_mappers_path(project) %>');
});

app/views/meme_mappers/edit.js.erb
(function () {
  $('#modal .modal-header .heading').text('<%= escape_javascript(t("tools.meme_mapper.save_search")) %>');

  var container = $('#modal .main');
  container.html('<%= escape_javascript(render('meme_mappers/edit')) %>');
})();

app/views/meme_mappers/index.js.erb
(function () {
  $('#modal').modal('hide');

  var container = $('#mememapper .content-placeholder');
  container.html('<%= escape_javascript(render('index')) %>');

  container.find('a').bind('ajax:beforeSend', function () {
    container.find('.spinning').removeClass('hide');
  });

  container.find('a').bind('ajax:complete', function () {
    container.find('.spinning').addClass('hide');
  });
})();

app/views/meme_mappers/new.js.erb
(function () {
  var container = $('#mememapper .content-placeholder');
  container.html('<%= escape_javascript(render('new')) %>');

  var form = container.find('form');

  form.on('submit', function (e) {
    $(this).find('.spinning').removeClass('hide');

    var button = $(this).find('button');
    button.attr('disabled', true);
    button.find('.text').text('<%= escape_javascript(t("tools.meme_mapper.fetching")) %>');
  });
})();

app/views/meme_mappers/show.js.erb
(function () {
  $('#modal').modal('hide');

  var container = $('#mememapper .content-placeholder');
  container.html('<%= escape_javascript(render('show')) %>');

  container.find('a').bind('ajax:beforeSend', function () {
    container.find('.spinning').removeClass('hide');
  });

  container.find('a').bind('ajax:complete', function () {
    container.find('.spinning').addClass('hide');
  });
})();