config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'projects#index'

  get '/ui' => 'pages#ui'
  post '/tools/detect-bias' => 'tools#detect_bias'

  devise_for :users,
            path_names: { 
              sign_up: 'register', 
              sign_in: 'login', 
              sign_out: 'logout' 
            },
            controllers: { registrations: 'users', sessions: 'sessions' }

  resources :projects do
    get :pads
    get :checklist_report

    resources :collaborators, only: [:index, :destroy] do
      post :invite, on: :collection
      get :suggest, on: :collection
      put :promote, on: :member
    end

    resources :checklists, only: [:index] do
      put :check, on: :collection
    end

    resources :project_pads, only: [:new, :create, :edit, :update, :destroy]
    resources :queries
    resources :meme_mappers
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  public     :boolean          default(FALSE), not null
#

class Project < ApplicationRecord
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  has_many :project_checklists, dependent: :destroy
  has_many :project_pads, dependent: :destroy
  has_many :queries, dependent: :destroy
  has_many :meme_mappers, dependent: :destroy

  alias_attribute :checklists, :project_checklists

  validates :name, presence: true

  scope :collaborating, -> (user) { joins(:collaborators).where(collaborators: { user_id: user.id }) }
  scope :lead, -> { joins(:collaborators).where(collaborators: { lead: true }) }
  scope :nonlead, -> { joins(:collaborators).where(collaborators: { lead: false }) }

  def lead_collaborators
    collaborators.where(lead: true)
  end

  def lead
    lead_collaborators.first.try(:user)
  end

  def primary_pad
    project_pads.order(:index).first
  end

  def has_checklist?(checklist)
    Project.joins(:project_checklists).where(id: id, checklists: { checklist_id: checklist.id }).present?
  end

  def progress
    return 0 unless checklists.present?
    total_item_count = checklists.reduce(0) { |total, chklst| total + chklst.item_count }
    total_checked_count = checklists.reduce(0) { |total, chklst| total + chklst.checked_count }
    value = total_checked_count.to_f / total_item_count * 100
    value.nan? ? 0 : value
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include EtherpadConcern

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  helper_method :presenter

  def index
    authorize(Project)
    projects = policy_scope(Project.all)

    @public_projects = projects.where(public: true).order(:name)

    if current_user.present?
      @lead_projects = projects.collaborating(current_user).lead.order(:name)
      @shared_projects = projects.collaborating(current_user).nonlead.order(:name)
    end
  end

  def new
    @form = ProjectForm.new(project: Project.new, user: current_user)
    authorize(@form.project)
  end

  def create
    @form = ProjectForm.new(form_params(Project.new))
    authorize(@form.project)
    if @form.valid? && save_form
      redirect_to project_path(@form.project)
    else
      render :new
    end
  end

  def show
    @project = find_project
  end

  def edit
    project = find_project
    @form = ProjectForm.new(project: project, user: current_user)
  end

  def update
    project = find_project
    @form = ProjectForm.new(form_params(project))
    if @form.valid? && save_form
      redirect_to project_path(project)
    else
      render :edit
    end
  end

  def destroy
    Projects::Delete.(project: find_project)
    redirect_to projects_path
  end

  def pads
    @project = find_project
    start_etherpad_session(presenter.current_pad) if policy(@project).collaborate?
    respond_to(&:js)
  end

  def checklist_report
    @project = find_project
    csv = Projects::Checklists.(project: @project, format: :csv)    
    csv_file_name = "project-#{@project.name.parameterize}-checklists-report.csv"
    respond_to do |format|
      format.html { send_data csv, type: 'text/csv', filename: csv_file_name, disposition: :attachment.to_s }
    end
  end

  private

  def find_project
    project = Project.find(params[:project_id] || params[:id])
    authorize(project)
    project
  end

  def save_form
    @form.save!
    true
  rescue ActiveRecord::RecordInvalid => e
    @errors = e.record.errors if e.record.present?
    false
  end

  def form_params(project)
    params.require(:project).permit(*ProjectForm.permit).merge(project: project, user: current_user).to_h
  end

  def presenter
    @presenter ||= ProjectPresenter.new(find_project, params[:pad])
  end
end

app/views/projects/_etherpad.html.erb
<ul class="nav nav-tabs">
  <% presenter.pad_list.each do |pad| %>
    <% if pad.active %>
      <li class="active">
        <%= link_to project_path(project, pad: pad.project_pad.id), class: 'dropdown dropdown-toggle', data: { toggle: 'dropdown' } do %>
          <%= pad.project_pad.name %>
          <span class="caret"></span>
        <% end %>

        <ul class="dropdown-menu">
          <% if policy(pad.project_pad).edit? %>
            <li>
              <%= link_to t('projects.show.edit_button'), edit_project_project_pad_path(project, pad.project_pad), remote: true, data: { toggle: 'modal', target: '#modal' } %>
            </li>
          <% end %>

          <% if policy(pad.project_pad).destroy? %>
            <li class="divider"></li>
            <li>
              <%= link_to t('projects.show.delete_button'), project_project_pad_path(project, pad.project_pad), method: :delete, remote: true, data: { confirm: t('projects.show.delete_confirm') } %>
            </li>
          <% end %>
        </ul>
      </li>
    <% else %>
      <li>
        <%= link_to pad.project_pad.name, project_pads_path(project, pad: pad.project_pad.id), remote: true %>
      </li>
    <% end %>
  <% end %>

  <% if policy(ProjectPad.new(project: project)).create? %>
    <li>
      <%= link_to t('projects.show.add_button'), new_project_project_pad_path(project), remote: true, data: { toggle: 'modal', target: '#modal' } %>
    </li>
  <% end %>
</ul>

<div id="etherpad" class="etherpad-block"></div>

<% unless policy(project).collaborate? %>
  <%= raw presenter.pad_content %>
<% end %>

app/views/projects/_form.html.erb
<%= render 'shared/errors', errors: @errors || @form.errors %>

<div class="form-group">
  <label for="name"><%= t('projects.form.name') %></label>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="spacing-v">
  <%= f.check_box :public, class: 'input-checkbox', id: 'project-public' %>
  <label class="input-checkbox-label" for="project-public"><%= t('projects.form.public') %></label>
</div>

<% if policy(Checklist).index? or @form.project.try(:new_record?) %>
  <div class="form-group">
    <label><%= t('projects.form.checklists') %></label>

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <%= f.collection_check_boxes :selected_checklists, @form.global_checklists, :id, :name do |item| %>
        <% presenter = @form.checklist_presenters[item.value] %>
        <% if presenter.enabled or presenter.attached %>
          <div class="panel panel-secondary">
            <div class="panel-heading" role="tab" id="headingOne<%= item.value %>">
              <h4 class="panel-title">
                <%= item.check_box %>
                <label for="project-demo-1" data-toggle="collapse" data-parent="#accordion" href="#collapseOne<%= item.value %>" aria-expanded="true" aria-controls="collapseOne<%= item.value %>" role="button">
                  <%= item.label %> <small>(<i><%= presenter.global_name %>, <%= DateTime.strptime(presenter.created_at.to_s,'%Y-%m-%d %H:%M:%S %Z').strftime('%Y-%m-%d %Z') %>, <%= presenter.enabled ? 'enabled' : 'disabled' %></i>)</small>
                </label>
              </h4>
            </div>
            <div id="collapseOne<%= item.value %>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne<%= item.value %>">
              <div class="panel-body">
                <% @form.checklist_items[item.value].each do |entry| %>
                  <p>
                    <span class="fa fa-check gray-steel"></span> <%= entry[:item] %>
                    <% if entry[:help].present? %>
                      <a href="#" class="info-checkbox" data-toggle="tooltip" data-html="true" data-container="body" data-trigger="manual" title="<%= entry[:help] %>">
                        <span class="glyphicon glyphicon-info-sign"></span>
                      </a>
                    <% end %>
                  </p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div> <!-- /.panel -->
      <% end %>

      <%= f.collection_check_boxes :zombie_checklists, @form.deleted_global_checklists, :id, :name do |item| %>
        <div class="panel panel-secondary">
          <div class="panel-heading" role="tab" id="headingTwo<%= item.value %>">
            <h4 class="panel-title">
              <%= item.check_box %>
              <label for="project-demo-2" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo<%= item.value %>" aria-expanded="true" aria-controls="collapseTwo<%= item.value %>" role="button">
                <%= item.label %> <small class='text-danger'>(*<%= t('projects.form.zombie_checklist_message') %>)</small>
              </label>
            </h4>
          </div>
          <div id="collapseTwo<%= item.value %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo<%= item.value %>">
            <div class="panel-body">
              <% @form.zombie_checklist_items[item.value].each do |entry| %>
                <p>
                  &#x2713; <%= entry[:item] %>
                  <% if entry[:help].present? %>
                    <a href="#" data-toggle="tooltip" data-html="true" title="<%= entry[:help] %>">
                      <span class="glyphicon glyphicon-info-sign"></span>
                    </a>
                  <% end %>
                </p>
              <% end %>
            </div>
          </div>
        </div> <!-- /.panel -->
      <% end %>
    </div> <!-- ./panel-group -->
  </div>

  <div class="form-group text-center">
    <span class="spacing-half-h">
      <%= link_to t('projects.form.cancel'), :back, class: "btn btn-dull--light" %>
    </span>
    <span class="spacing-half-h">
      <%= f.button defined?(submit_text) ? submit_text : t('projects.form.submit'), type: 'submit', class: "btn btn-primary" %>
    </span>
  </div>
<% end %>

app/views/projects/_header.html.erb
<div class="etherpad-title-block flex flex-align-baseline">
  <h1 class="h2">
    <span class="fa fa-file-text project-title-icon"></span>
    <span><%= @project.name %></span>
  </h1>
  <span class="spacing-h"></span>

  <% if policy(@project).edit? %>
    <%= link_to edit_project_path(@project), :class => 'btn btn-link' do %>
      <span class="fa fa-pencil"></span>
      <%= t('projects.show.edit_button') %>
    <% end %>
  <% end %>

  <% if policy(@project).destroy? %>
    <%= link_to project_path(@project), method: :delete, data: { confirm: t('projects.show.delete_confirm') }, :class => 'btn btn-link' do %>
      <span class="fa fa-close"></span>
      <%= t('projects.show.delete_button') %>
    <% end %>
  <% end %>

  <% if policy(@project).collaborate? %>
    <%= link_to project_collaborators_path(@project), remote: true, data: { toggle: 'modal', target: '#modal' }, :class => 'btn btn-link' do %>
      <span class="fa fa-users"></span>
      <%= t('projects.show.collaborators_button') %>
    <% end %>
  <% end %>
</div>

app/views/projects/_list.html.erb
<% if projects.present? %>
  <% for project in projects do %>
    <div class="gutter">
      <%= link_to project_path(project), class: 'project-each' do %>
        <span class="fa fa-file-text-o project-each-icon"></span>
      <% end %>
      <div class="project-caption">
        <strong><%= project.name %></strong>
        <div class="font-size-sm"><%= project.created_at %></div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="col-xs-12 spacing-v">
    <em><%= empty_message %></em>
  </div>
<% end %>

app/views/projects/_sidebar.html.erb
<div class="sidebar">
  <ul class="nav nav-pills" role="tablist">
    <% if @project.checklists.empty? %>
      <li role="presentation" class="active">
    <% else %>
      <li role="presentation">
    <% end %>
    <%= link_to t('projects.show.tools.media_cloud'), new_project_query_path(@project), id: 'mediacloud-tab-link', remote: true, data: { toggle: 'tab', target: '#mediacloud-tab' } %>
      </li>

      <li role="presentation">
        <a href="#biasdetector-tab" aria-controls="biasdetector-tab" role="tab" data-toggle="tab"><%= t('projects.show.tools.bias_detector') %></a>
      </li>

      <li role="presentation">
        <%= link_to t('projects.show.tools.meme_mapper'), new_project_meme_mapper_path(@project), id: 'mememapper-tab-link', remote: true, data: { toggle: 'tab', target: '#mememapper-tab' } %>
      </li>

    <% if @project.checklists.present? %>
      <li role="presentation" class="active">
        <a href="#checklists-tab" aria-controls="checklists-tab" role="tab" data-toggle="tab">
          <%= t('projects.show.tools.checklist') %>
          <span class="badge bg-alert">
            <%= presenter.checklist_count %>
          </span>
        </a>
      </li>
    <% end %>
  </ul>

  <div class="tab-content">
    <% if @project.checklists.empty? %>
      <div role="tabpanel" class="tab-pane active" id="mediacloud-tab">
    <% else %>
      <div role="tabpanel" class="tab-pane" id="mediacloud-tab">
    <% end %>
        <div id="mediacloud">
          <div class="errors-placeholder"></div>
          <div class="content-placeholder"></div>
        </div>
      </div>

    <div role="tabpanel" class="tab-pane" id="biasdetector-tab">
      <%= render 'tools/detect_bias' %>
    </div>

    <div role="tabpanel" class="tab-pane" id="mememapper-tab">
      <div id="mememapper">
        <div class="errors-placeholder"></div>
        <div class="content-placeholder"></div>
      </div>
    </div>

    <% if @project.checklists.present? %>
      <div role="tabpanel" class="tab-pane active" id="checklists-tab">
        <div id="checklists">
          <div class="errors-placeholder"></div>
          <div class="lists"></div>
        </div>
      </div>
    <% end %>
  </div>
</div> <!-- /.sidebar -->

app/views/projects/edit.html.erb
<h1><%= t('projects.edit.heading') %></h1>

<%= form_for @form, as: :project, url: project_path, method: :put do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-sm-8">
    <div class="spacing-v">
      <% if user_signed_in? && current_user.name.present? %>
        <h3><%= t('landing.welcome_user', name: current_user.name) %></h3>
      <% else %>
        <h3><%= raw t('landing.welcome_anonymous', link: link_to('Global Voices', 'https://globalvoices.org', target: '_blank')) %></h3>
      <% end %>

      <p>
        <%= t('landing.intro') %>
        <%= link_to t('landing.read_more'), 'https://newsframes.globalvoices.org/about/', target: '_blank' %>
        <%= t('landing.read_more_cont') %>
      </p>
    </div>
    <div class="spacing-2-v">
      <h3><%= t('projects.index.lead.heading') %></h3>

      <div class="row flex flex-wrap">
        <div class="gutter">
          <%= link_to new_project_path, class: 'project-each project-each--create' do %>
            <span class="fa fa-plus icon-left-sm"></span>
            <%= t('projects.index.create_button') %>
          <% end %>
        </div>

        <%= render 'list', projects: @lead_projects, empty_message: t('projects.index.lead.empty_message') %>
      </div>
    </div>

    <% if user_signed_in? %>
      <div class="spacing-2-v">
        <h3><%= t('projects.index.shared.heading') %></h3>

        <div class="row flex flex-wrap">
          <%= render 'list', projects: @shared_projects, empty_message: t('projects.index.shared.empty_message') %>
        </div>
      </div>
    <% end %>

    <% if @public_projects.present? %>
      <div class="spacing-2-v project-public-block">
        <h3><%= t('projects.index.public.heading') %></h3>

        <div class="row flex flex-wrap">
          <%= render 'list', projects: @public_projects, empty_message: nil %>
        </div>
      </div>
    <% end %>
  </div> <!-- /col-sm-8 -->
  <div class="col-sm-4 sidebar-wrap">
    <div class="sidebar">
      <h2 class="h4"><%= t('projects.sidebar.learn_more') %></h2>
      <p><%= raw t('projects.sidebar.intro', link: link_to('Global Voices', 'https://globalvoices.org/', target: '_blank')) %></p>

      <ul>
        <% for item in t('projects.sidebar.links') do %>
          <li>
            <%= link_to item[:title], item[:url], class: 'font-bold', target: '_blank' %>
          </li>
        <% end %>
      </ul>
    </div> <!-- /.sidebar -->
  </div>
</div> <!-- /.row -->

app/views/projects/new.html.erb
<h1><%= t('projects.new.heading') %></h1>

<%= form_for @form, as: :project, url: projects_path do |f| %>
  <%= render 'form', f: f, submit_text: t('projects.form.create') %>
<% end %>

app/views/projects/pads.js.erb
(function () {
  var container = $('#etherpad-frame');
  container.html('<%= escape_javascript(render('etherpad', project: @project)) %>');
  <% if policy(@project).collaborate? %>
    $('#etherpad').pad({
      padId: '<%= raw presenter.current_pad.pad_id %>',
      host: '<%= raw ENV['ETHERPAD_URL'] %>',
      showControls: true,
      userName: '<%= raw current_user.short_name %>'
    });
  <% end %>
})();

app/views/projects/show.html.erb
<% content_for :body_class, "body-full-screen" %>

<% content_for :head do %>

  <% if policy(@project).collaborate? %>
    <script>
     $(function () {       
      <% if @project.checklists.present? %>
        $.getScript('<%= j project_checklists_path(@project) %>');
      <% else %>
        $.getScript('<%= j new_project_query_path(@project) %>');
      <% end %>    
     });
    </script>
  <% end %>
  <script>
    $(function(){
      // Toggle width of etherpad and sidebar to 50%
      $(".js-toggle-width-half").on("click", function(e){
        e.preventDefault();
        $(this).toggleClass('toggle-width-half--compress');
        $('.sidebar-wrap-flex').removeClass("js-sidebar-width-tool js-sidebar-width-etherpad").toggleClass('js-sidebar-width-half');
        $('.etherpad-wrap-flex').removeClass("js-etherpad-width-tool js-etherpad-width-etherpad").toggleClass('js-etherpad-width-half');
      });

      // Toggle width of sidebar
      $(".js-toggle-width-tool").on("click", function(e){
        e.preventDefault();
        $('.sidebar-wrap-flex').removeClass("js-sidebar-width-half js-sidebar-width-etherpad").toggleClass('js-sidebar-width-tool');
        $('.etherpad-wrap-flex').removeClass("js-etherpad-width-half js-etherpad-width-etherpad").toggleClass('js-etherpad-width-tool');
      });

      // Toggle width of etherpad
      $(".js-toggle-width-etherpad").on("click", function(e){
        e.preventDefault();
        //$(this).toggleClass('toggle-width-etherpad--compress');
        $('.sidebar-wrap-flex').removeClass("js-sidebar-width-half js-sidebar-width-tool").toggleClass('js-sidebar-width-etherpad');
        $('.etherpad-wrap-flex').removeClass("js-etherpad-width-half js-etherpad-width-tool").toggleClass('js-etherpad-width-etherpad');
      });

      // show etherpad
      $.getScript('<%= j project_pads_path(@project) %>');   
    });
  </script>

<% end %>

<% content_for :body do %>
  <%= render 'shared/modal' %>
<% end %>

<div class="clearfix container-etherpad">
  <% if policy(@project).collaborate? %>
    <div class="col-sm-8 etherpad-wrap-flex">
  <% else %>
    <div class="col-sm-12 etherpad-wrap-flex">
  <% end %>
      <div>
        <%= render 'header' %>
        <hr>
        <div id="etherpad-frame">
        </div>
      </div>
    </div> <!-- /.col -->

  <% if policy(@project).collaborate? %>
    <div class="col-sm-4 sidebar-wrap sidebar-wrap-flex">
      <div class="toggle-panel-icon-wrap">
        <a href="" class="fa toggle-panel-icon toggle-width-half js-toggle-width-half"></a>
        <a href="" class="fa toggle-panel-icon toggle-width-tool js-toggle-width-tool"></a>
        <a href="" class="fa toggle-panel-icon toggle-width-etherpad js-toggle-width-etherpad"></a>
      </div>
      <%= render 'sidebar' %>
    </div> <!-- /.col -->
  <% end %>
</div> <!-- /.container-etherpad -->