config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'projects#index'

  get '/ui' => 'pages#ui'
  post '/tools/detect-bias' => 'tools#detect_bias'

  devise_for :users,
            path_names: { 
              sign_up: 'register', 
              sign_in: 'login', 
              sign_out: 'logout' 
            },
            controllers: { registrations: 'users', sessions: 'sessions' }

  resources :projects do
    get :pads
    get :checklist_report

    resources :collaborators, only: [:index, :destroy] do
      post :invite, on: :collection
      get :suggest, on: :collection
      put :promote, on: :member
    end

    resources :checklists, only: [:index] do
      put :check, on: :collection
    end

    resources :project_pads, only: [:new, :create, :edit, :update, :destroy]
    resources :queries
    resources :meme_mappers
  end
end

app/models/checklist.rb
# == Schema Information
#
# Table name: checklists
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  enabled    :boolean          default(TRUE), not null
#

class Checklist < ApplicationRecord

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :checklist_items, dependent: :destroy
  has_many :project_checklists, dependent: :nullify
  alias_attribute :items, :checklist_items

  translates :name
  globalize_accessors :locales => [:en_US], :attributes => [:name]

  def cache_key
    super + '-' + Globalize.locale.to_s
  end

  def available_translations
    self.translations.map(&:locale).reject { |entry| entry == 'en_US' || entry == 'en' }
  end

  def with_translation(locale, fallback_locale = nil)
    model = self.translations.where(locale: locale).first
    return model if model.present?
    return nil unless fallback_locale.present?
    self.translations.where(locale: fallback_locale).first
  end

  def with_translation_in_current_locale(fallback_locale='en_US')
    current_locale = I18n.locale.to_s
    with_translation(current_locale, fallback_locale)
  end

end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  after_action :verify_authorized

  helper_method :checklists_form, :collaborator, :project

  def policy_class
    CollaboratorChecklistPolicy
  end

  def index
    authorize(CollaboratorChecklist.new(collaborator: collaborator), :index?)
    checklists_form
    respond_to(&:js)
  end

  def check
    authorize(CollaboratorChecklist.new(collaborator: collaborator), :check_item?)
    @checklists_form = ProjectChecklistsForm.new(form_params(collaborator))
    @errors = @checklists_form.errors unless @checklists_form.valid?
    @checklists_form.save!
  rescue ActiveRecord::RecordInvalid => e
    @errors = e.record.errors
  ensure
    respond_to(&:js)
  end

  private

  def form_params(collaborator)
    params.require(:collaborator_checklist).permit(*ProjectChecklistsForm.permit).merge(collaborator: collaborator, user: current_user).to_h
  end

  def checklists_form
    @checklists_form ||= ProjectChecklistsForm.new(collaborator: collaborator) if collaborator.present?
  end

  def project
    @project ||= Project.find(params[:project_id])
  end

  def collaborator
    @collaborator ||= Collaborator.find_by(project_id: params[:project_id], user_id: current_user.id)
  end
end

app/views/checklists/_list.html.erb
<div class="spacing-2-v">
  <h2 class="h4 margin-reset"><%= t('checklists.list.heading') %></h2>
</div>

<%= render 'report' %>

<% if checklists_form.present? %>
  <%= form_for checklists_form, as: :collaborator_checklist, url: check_project_checklists_path(project), remote: true, method: :put do |f| %>
    <div class="panel-group" role="tablist" aria-multiselectable="true">
      <% for checklist, i in checklists_form.checklists.each_with_index do %>
        <div class="panel panel-secondary">
          <div class="panel-heading" role="tab button" data-toggle="collapse" data-parent=".panel-group" href="#<%= dom_id(checklist) %>">
            <h4 class="panel-title">
              <label aria-expanded="true" role="button">
                <% if policy(project).checklist_report? %>
                  <%= checklist.with_translation_in_current_locale.name %> (<%= checklist.progress.round(2) %>% <%= t('checklists.list.complete') %>, <%= checklist.project_checklist.progress.round(2) %>% <%= t('checklists.list.complete_across_team') %>)
                <% else %>
                  <%= checklist.with_translation_in_current_locale.name %> (<%= checklist.progress.round(2) %>% <%= t('checklists.list.complete') %>)
                <% end %>
              </label>
            </h4>
          </div> <!-- ./panel-heading -->

          <div id="<%= dom_id(checklist) %>" class="panel-collapse collapse <%= i == 0 ? 'in' : '' %>" role="tabpanel">
            <div class="panel-body">
              <fieldset <% unless policy(checklist).check_item? %>disabled<% end %>>
                <%= f.collection_check_boxes :selected_checklist_items, checklist.items.sort_by(&:created_at), :id, :item_with_translation_in_current_locale do |entry| %>
                  <p>
                    <div class="flex">
                      <label class="flex-1">
                        <%= entry.check_box class: 'input-checkbox' %>
                        <%= entry.label class: 'input-checkbox-label' %>
                      </label>

                      <% if entry.object.help_with_translation_in_current_locale.present? %>
                        <a href="#" data-toggle="tooltip" data-html="true" data-container="body" data-trigger="manual" title="<%= entry.object.help_with_translation_in_current_locale %>" class="info-checkbox">
                          <span class="glyphicon glyphicon-info-sign"></span>
                        </a>
                      <% end %>
                    </div>
                  </p>
                <% end %>
              </fieldset>
            </div> <!-- ./panel-body -->
          </div> <!-- ./panel-collapse -->
        </div> <!-- ./panel -->
      <% end %>
    </div> <!-- ./panel-group -->

    <div class="form-group text-center">
      <%= f.button t('checklists.list.submit_button'), type: 'submit', class: 'btn btn-primary' %>
    </div>

  <% end %>
<% end %>

app/views/checklists/_report.html.erb
<% if policy(project).checklist_report? %>
  <div class="spacing-half">
    <p>
      (<%= project.progress.round(2) %>% <%= t('checklists.list.complete_across_team') %>)
      <a href="<%= project_checklist_report_path(project.id) %>"><%= t('checklists.list.run_report') %></a>
    </p>
  </div>
<% end %>

app/views/checklists/check.js.erb
$('#checklists .lists').html('<%= escape_javascript(render('checklists/list', checklists_form: checklists_form)) %>');

<% if @errors.present? %>
$('#checklists .errors-placeholder').html('<%= escape_javascript(render('shared/errors', errors: @errors)) %>');
<% end %>

app/views/checklists/index.js.erb
$('#checklists .lists').html('<%= escape_javascript(render('checklists/list', checklists_form: checklists_form)) %>');

tooltipPersist();