config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'projects#index'

  get '/ui' => 'pages#ui'
  post '/tools/detect-bias' => 'tools#detect_bias'

  devise_for :users,
            path_names: { 
              sign_up: 'register', 
              sign_in: 'login', 
              sign_out: 'logout' 
            },
            controllers: { registrations: 'users', sessions: 'sessions' }

  resources :projects do
    get :pads
    get :checklist_report

    resources :collaborators, only: [:index, :destroy] do
      post :invite, on: :collection
      get :suggest, on: :collection
      put :promote, on: :member
    end

    resources :checklists, only: [:index] do
      put :check, on: :collection
    end

    resources :project_pads, only: [:new, :create, :edit, :update, :destroy]
    resources :queries
    resources :meme_mappers
  end
end

app/models/query.rb
# == Schema Information
#
# Table name: queries
#
#  id              :integer          not null, primary key
#  project_id      :integer          not null
#  media_cloud_url :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  name            :string
#  full_data       :boolean          default(FALSE), not null
#  serialized_data :binary
#  migrated        :boolean          default(FALSE), not null
#
# Foreign Keys
#
#  fk_rails_177ec16807  (project_id => projects.id)
#

class Query < ApplicationRecord
  QUERY_TYPES = [:storycount, :wordcount, :stories]

  attr_reader :term

  belongs_to :project

  validates :media_cloud_url, presence: true

  def term=(value)
    value = value.strip
    if value =~ /^http/
      self.media_cloud_url = value
    else
      start_date = (Date.today - 1.year).to_s
      end_date = Date.today.to_s
      q = [{
        'label' => value,
        'q' => value,
        'startDate' => start_date,
        'endDate' => end_date,
        'sources' => [],
        'collections' => [9139487],
        'color' => '%23000000'
      }]
      self.media_cloud_url = "https://explorer.mediacloud.org/#/queries/search?q=#{q.to_json}"
    end
  end

  def data
    @data ||= JSON.parse(ActiveSupport::Gzip.decompress(self.serialized_data)).with_indifferent_access
  end

  def data=(data)
    @data = data
    self.serialized_data = ActiveSupport::Gzip.compress(JSON.dump(data))
  end

  def query_params
    @query_params ||= MediaCloud.parse_url(media_cloud_url)
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  helper_method :filter, :presenter, :project, :query
  before_action -> { authorize(project, :collaborate?) }

  def index
    @queries = project.queries.sort_by do |query|
      [
        QueryPresenter.new(query).query_label.gsub('"', '').downcase,
        -query.created_at.to_i
      ]
    end
    respond_to(&:js)
  end

  def new
    @query = Query.new(project: project)
    respond_to(&:js)
  end

  def create
    @query = Query.new(query_params)
    Queries::Save.(query: @query, fetch_data: true)
    redirect_to project_query_path(project, @query)
  rescue ActiveRecord::RecordInvalid
    render_error
  rescue MediaCloud::ParseError
    render_error('^Unable to parse URL')
  rescue Net::ReadTimeout
    render_error('^Query timeout. Please try using Media Cloud directly')
  rescue MediaCloudQuery::APIError => err
    puts err
    Rollbar.error(err)
    render_error('^Media Cloud not responding')
  rescue Exception => err
    Rollbar.error(err)
    Rails.logger.error(err)
    render_error('^Unexpected error')
  end

  def show
    respond_to do |format|
      format.js
      format.csv do
        begin
          Queries::DownloadFullData.(query: query)
          send_data(presenter.render_csv, type: 'text/csv', filename: csv_file_name, disposition: :attachment.to_s)
        rescue MediaCloudQuery::APIError
          puts err
          Rollbar.error(err)
          flash[:error] = 'Media Cloud not responding'
          redirect_to project_path(project)
        end
      end
    end
  end

  def edit
  end

  def update
    query.update_attributes(query_params)
    Queries::Save.(query: query, fetch_data: false)
    redirect_to project_query_path(project, query)
  rescue ActiveRecord::RecordInvalid
    render :edit
    respond_to(&:js)
  end

  def destroy
    query.destroy!
    respond_to(&:js)
  end

  private

  def project
    @project ||= Project.find(params[:project_id])
  end

  def query
    @query ||= Query.find(params[:id])
  end

  def query_params
    params.require(:query).permit(:name, :term).merge(project: project)
  end

  def filter
    params[:filter]
  end

  def presenter
    @presenter ||= QueryPresenter.new(query, filter)
  end

  def csv_file_name
    filterName = filter[:frequency].present? ? :frequency.to_s : :stories.to_s
    "#{project.name}-#{query.name}-#{DateTime.now}-#{filterName}.csv"
  end

  def render_error(error = '')
    @query.errors.add(:media_cloud_url, error) if error.present?
    render :new
    respond_to(&:js)
  end
end

app/views/queries/_edit.html.erb
<%= form_for [project, query], remote: true do |f| %>
  <div class="modal-body">
    <div class="errors-placeholder"></div>

    <%= render 'shared/errors', errors: query.errors %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "e.g #{presenter.query_label}", class: 'form-control' %>
    </div>
  </div>

  <div class="modal-footer">
    <div class="form-group">
      <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('general.close') %></button>
      <%= f.submit t('tools.media_cloud.save'), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/queries/_index.html.erb
<div class="spacing-v"></div>
<div class="pull-right">
  <%= link_to new_project_query_path(project), remote: true do %>
    <span class="fa fa-close trigger-close-searches"></span>
  <% end %>
</div>

<h2 class="h4"><%= t('tools.media_cloud.heading') %></h2>
<div class="spacing-half-v"></div>
<h3 class="h5"><%= t('tools.media_cloud.saved_searches') %></h3>

<table class="table table-hover table-striped table-bordered">
  <tbody>
    <% for query in @queries do %>
      <tr>
        <td>
          <%= query.created_at %>
        </td>
        <td>
          <%= link_to QueryPresenter.new(query).query_label, project_query_path(project, query), remote: true %>
        </td>
        <td>
          <%= link_to t('tools.media_cloud.edit'), edit_project_query_path(project, query), remote: true, data: { toggle: 'modal', target: '#modal' } %>
          <%= link_to t('tools.media_cloud.delete'), project_query_path(project, query), method: :delete, remote: true, data: { confirm: t('tools.media_cloud.confirm') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/queries/_new.html.erb
<div class="flex flex-wrap spacing-2-v">
  <h2 class="h4 margin-reset"><%= t('tools.media_cloud.heading') %></h2>
  <ul class="list-unstyled clearfix list-mc-searches">
    <li class="pull-right font-size-sm">
      <%= link_to t('tools.media_cloud.saved_searches'), project_queries_path(project), class: '', remote: true %>
      <span>|</span>
      <a href="https://explorer.mediacloud.org" target="_blank">
        <%= image_tag 'logos/mm-logo.png', alt: '', width: '32' %>
        <span class="fa fa-external-link"></span>
      </a>
    </li>
  </ul>
</div>

<%= form_for [project, @query], remote: true do |f| %>
  <%= render 'shared/errors', errors: @query.errors %>

  <%= f.label :media_cloud_url, t('tools.media_cloud.query_term') %>
  <div class="form-group flex row-sm flex-align-center">
    <div class="gutter-sm flex-1">
      <%= f.text_field :term, placeholder: 'e.g. https://explorer.mediacloud.org/...', class: 'form-control' %>
    </div>
    <div class="gutter-sm">
      <button class="btn btn-primary">
        <i class="glyphicon glyphicon-refresh spinning hide"></i>
        <span class="text"><%= t('tools.media_cloud.submit') %></span>
      </button>
    </div>
  </div>
<% end %>

<div class="well">
  <p>
    <%= raw t('tools.media_cloud.instructions') %>
  </p>
</div>

app/views/queries/_show.html.erb
<div class="spacing-2-v font-size-sm clearfix">
  <div class="pull-right">
    <span>
      <%= link_to 'New search', new_project_query_path(project), remote: true %>
    </span>
    <span>|</span>
    <span>
      <%= link_to 'Saved searches', project_queries_path(project), remote: true %>
      <span>|</span>
      <a href="<%= query.media_cloud_url %>" target="_blank">
        <%= image_tag 'logos/mm-logo.png', alt: '', width: '32' %>
        <span class="fa fa-external-link"></span>
      </a>
    </span>
  </div>
</div>

<p>
  <% if query.migrated %>
  <span class="highlight">[DASHBOARD MIGRATION]</span>
  <br>
  <% end %>
  <%= query.created_at %>
  <strong><%= presenter.query_label %></strong>
  <br>
  <%= link_to query.media_cloud_url, query.media_cloud_url, class: 'ellipsis full-width', target: '_blank' %>
</p>

<% unless query.name.present? %>
  <p>
    <%= link_to 'Save Search', edit_project_query_path(project, query), class: 'btn btn-primary', remote: true, data: { toggle: 'modal', target: '#modal' } %>
  </p>
<% end %>

<div class="well">
  <div class="h5"><strong>Summary of results</strong></div>
  <table class="table margin-reset">
    <tbody>
      <% for results, i in presenter.query_data(:storycount).each_with_index do %>
        <tr>
          <td>
            <span style="color: #<%= presenter.query_params[i].color %>">
              <%= presenter.query_names[i] %>:
            </span>

            <%= results['count'] %>
            stories found across
            <% if presenter.query_params[i].sources.present? %>
              <%= pluralize(*presenter.query_params[i].sources) %>
            <% else %>
              all collections
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="table-frequency-lg">
  <%= render 'queries/widgets/frequency', presenter: presenter, slice: 0..-1, large_window: true %>
</div>

<div class="table-frequency-sm">
  <%= render 'queries/widgets/frequency', presenter: presenter, slice: 0..10, ellipsis: true %>
</div>

<%= render 'queries/widgets/stories', presenter: presenter, slice: 0..10 %>

app/views/queries/destroy.js.erb
$(function () {
  $.getScript('<%= j project_queries_path(project) %>');
});

app/views/queries/edit.js.erb
(function () {
  $('#modal .modal-header .heading').text('<%= escape_javascript(t("tools.media_cloud.save_search")) %>');

  var container = $('#modal .main');
  container.html('<%= escape_javascript(render('queries/edit')) %>');
})();

app/views/queries/index.js.erb
(function () {
  var container = $('#mediacloud .content-placeholder');
  container.html('<%= escape_javascript(render('index')) %>');
})();

app/views/queries/new.js.erb
(function () {
  var container = $('#mediacloud .content-placeholder');
  container.html('<%= escape_javascript(render('new')) %>');

  var form = container.find('form');

  form.on('submit', function (e) {
    $(this).find('.spinning').removeClass('hide');

    var button = $(this).find('button');
    button.attr('disabled', true);
    button.find('.text').text('<%= escape_javascript(t("tools.media_cloud.fetching")) %>');
  });
})();

app/views/queries/show.js.erb
(function () {
  $('#modal').modal('hide');

  var container = $('#mediacloud .content-placeholder');
  container.html('<%= escape_javascript(render('show')) %>');

  var form = container.find('#frequency-form')
  form.find('select').on('change', function () {
    form.submit();
  });
})();